console.log(Math.LN10);
console.log(Math.PI);
console.log(Math.SQRT2);
console.log(Math.sin(20));
console.log(Math.pow(4,2));
console.log(Math.random());
console.log(Math.ceil(1.75));
console.log(Math.floor(1.49));
console.log(Math.round(1.50));